[Writable]
LogLevel = "INFO"
  [Writable.StoreAndForward]
  Enabled = false
  RetryInterval = "5m"
  MaxRetryCount = 10
  [Writable.InsecureSecrets]
    [Writable.InsecureSecrets.DB]
    path = "redisdb"
      [Writable.InsecureSecrets.DB.Secrets]
      username = ""
      password = ""


[SecretStore]
Type = "vault"
Host = "localhost"
Port = 8200
Path = "app-rules-engine/"
Protocol = "http"
RootCaCertPath = ""
ServerName = ""
TokenFile = "/tmp/secrets-token.json"
  [SecretStore.Authentication]
  AuthType = "X-Vault-Token"

[Service]
HealthCheckInterval = "10s"
Host = "localhost"
Port = 59795
ServerBindAddr = "" 
StartupMsg = "Camera image viewer Service started"
RequestTimeout = "30s"
MaxRequestSize = 0
MaxResultCount = 0
Timeout = "30s"

[Registry]
Host = 'localhost'
Port = 8500
Type = 'consul'

[Logging]
EnableRemote = false
File = ''

[Database]
Type = "redisdb"
Host = "localhost"
Port = 6379
Timeout = "30s"

[Clients]
  [Clients.core-metadata]
  Protocol = "http"
  Host = "localhost"
  Port = 59881
  
[Trigger]
Type="edgex-messagebus"
  [Trigger.EdgexMessageBus]
  Type = "redis"
    [Trigger.EdgexMessageBus.SubscribeHost]
    Host = "localhost"
    Port = 6379
    Protocol = "redis"
    SubscribeTopics="edgex/events/#"
    [Trigger.EdgexMessageBus.PublishHost]
    Host = "localhost"
    Port = 6379
    Protocol = "redis"
    PublishTopic="example"
    [Trigger.EdgexMessageBus.Optional]
    authmode = "usernamepassword"  # requied for redis messagebus (secure or insecure).
    secretname = "redisdb"
 

[ApplicationSettings]
ResourceNames = "OnvifSnapshot"



